#
# This is a working example of using GitHub Actions to publish the docs
# to the GitHub Pages (gh_pages) branch.
#
# Remember to have a requirements.txt file with the required dependencies.
# This template ships with one by default.
#
# It is also recommendet to also copy the template with all branches, to
# have the gh-pages branch pre-made. This prevents possible errors.
#
name: Deploy Site

on: [push, pull_request]
permissions:
  contents: write

# on:
#   push:
#     paths:
#     - 'docs/**'
#     - 'mkdocs.yml'
#     - 'theme/**'
#     branches:
#     - master
#     #
#     # If your repository would have releases should you uncomment the below lines
#     # in order to ignore pushes caused by newly created releases.
#     #
#     #tags-ignore:
#     #- '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python setup.py develop
        #python -m pip install -r requirements.txt
    - name: Deploy Files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        python jarvis_leaderboard/rebuild.py
        mkdocs build
        git push -f origin nist-pages
        mkdocs gh-deploy  
